FROM registry.fedoraproject.org/fedora-toolbox:36

RUN dnf copr enable atim/bottom -y 
RUN dnf install -y \
    bat \
    ripgrep \
    fish \
    git \
    starship \
    lsd \
    exa \
    fd-find \
    git-delta \
    htop \
    bottom \
    zoxide

RUN dnf install -y \
    neovim \
    emacs-nox \
    kakoune \
    micro \

