FROM registry.fedoraproject.org/fedora-toolbox:36

RUN sudo dnf copr enable atim/bottom -y 
RUN # --mount=type=cache,target=/var/cache/dnf \
    sudo dnf install -y -v \
    bat \
    ripgrep \
    neovim \
    fish \
    git \
    starship \
    lsd \
    exa fd-find \
    git-delta \
    htop \
    bottom

